'use client';
import {useState} from 'react';
import {Link2, Package} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {connected,joinStatus,materialList,clearance,itemName,type JoinSide,type Bed,type Tent} from './model';
import {dispatch} from './store';
const fmt=(n:number)=>n.toLocaleString('pl-PL',{maximumFractionDigits:2});
export function Connections({beds,selected,tent}:{beds:Bed[];selected:Bed;tent:Tent}){
 const links=beds.filter(b=>connected(selected,b));
 const candidates=beds.filter(b=>b.id!==selected.id);
 return <section className="connection-panel"><div className="section-label"><Link2 size={16}/>Łączenie konstrukcji</div>{links.length>0&&<p className="connected-label">Połączona z: {links.map(b=>String(beds.indexOf(b)+1)).join(', ')}. Wspólne elementy liczymy raz.</p>}<p className="field-note">Dosuń dowolne boki lub wybierz stronę docelowej konstrukcji. Przyciąganie działa do 12 cm. Strony odnoszą się do namiotu. Zielone ✓: połączenie bez kolizji. Czerwone !: połączenie z błędem dopasowania.</p>{candidates.map(b=><div key={b.id}><p className="field-note">{beds.indexOf(b)+1}. {itemName(b)}</p><div className="join-sides">{([['left','Lewy'],['right','Prawy'],['back','Tył'],['front','Przód']] as [JoinSide,string][]).map(([side,label])=>{const status=joinStatus(beds,selected.id,b.id,side,tent);return <Button title={status.valid?'Połączenie możliwe bez kolizji':status.errors.join(' ')} className={status.valid?'join-valid':'join-invalid'} key={side} variant="outline" aria-label={label+' bok konstrukcji '+(beds.indexOf(b)+1)} onClick={()=>dispatch({type:'join',id:selected.id,targetId:b.id,side})}>{status.valid?'✓ ':'! '}{label}</Button>})}</div></div>)}<p className="field-note">Wspólne piony i belki na tej samej wysokości są scalane. Różne długości i obroty są dozwolone. Odsunięcie rozłącza konstrukcje.</p><div className="clearance-readout">Najbliższa ściana boczna lub tylna: <b>{fmt(clearance(selected,tent))} cm</b><span>Minimum: 20 cm. Przy wejściu: 0 cm.</span></div></section>
}
export function Materials({beds,invalid}:{beds:Bed[];invalid:boolean}){
 const m=materialList(beds),[rope,setRope]=useState(2);
 const cloth=new Map<string,number>();m.fabrics.forEach(f=>{const key=`${fmt(f.width)} × ${fmt(f.length)} cm`;cloth.set(key,(cloth.get(key)||0)+1)});
 return <section className="materials-panel"><div className="section-label"><Package size={17}/>Materiały — cały projekt</div>{!beds.length?<p className="field-note">Dodaj prycze, aby zobaczyć zestawienie.</p>:<><div className="material-total"><b>{m.poles} szt.</b><span>żerdzi Ø 8 cm · {fmt(m.meters)} m łącznie</span></div>{m.saved>0&&<p className="connected-label">Wspólne elementy: o {m.saved} szt. mniej.</p>}<Table aria-label="Żerdzie do budowy"><TableHeader><TableRow><TableHead>Element</TableHead><TableHead>Długość</TableHead><TableHead>Szt.</TableHead></TableRow></TableHeader><TableBody>{m.rows.map(r=><TableRow key={`${r.kind}:${r.length}`}><TableCell>{r.kind==='post'?'Pion':'Belka'}</TableCell><TableCell>{fmt(r.length)} cm</TableCell><TableCell>{r.count}</TableCell></TableRow>)}</TableBody></Table><dl><div><dt>Płótno na posłania</dt><dd>{fmt(m.fabricArea)} m²</dd></div>{[...cloth].map(([size,count])=><div key={size}><dt>{size}</dt><dd>{count} szt.</dd></div>)}{m.boards.length>0&&<><div><dt>Blaty półek (gr. 2,5 cm)</dt><dd>{fmt(m.boards.reduce((n,b)=>n+b.width*b.length/10000,0))} m²</dd></div>{m.boards.map((b,i)=><div key={'board'+i}><dt>{fmt(b.width)} × {fmt(b.length)} cm</dt><dd>1 szt.</dd></div>)}</>}<div><dt>Złącza na zaciosy</dt><dd>{m.joints} końców belek</dd></div></dl><label className="rope-estimate">Sznur na koniec belki (szacunek)<span><Input aria-label="Metry sznura na koniec belki" type="number" min="0" max="20" step="0.1" value={rope} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&n<=20)setRope(n)}}/>m</span></label><div className="rope-total">Sznur z 10% zapasu: <b>{fmt(Math.ceil(m.joints*rope*1.1*10)/10)} m</b></div><p className="field-note">Żerdzie: długości geometryczne modelu, bez zapasu na cięcie. Płótno: bez zakładek. Sznur: założenie {fmt(rope)} m na koniec belki; dopasuj do wiązań. Zestawienie nie obejmuje namiotu, stężeń ani innych elementów niewidocznych w modelu.</p>{invalid&&<p className="material-warning">Projekt ma błędy dopasowania. Ilości dotyczą obecnego układu i zmienią się po korekcie.</p>}</>}</section>
}

