export type Bed={id:string;levels:1|2;width:number;length:number;lower:number;upper:number;x:number;z:number;rotation:number};
export type Part={a:[number,number,number];b:[number,number,number];radius:number};
export const defaults={width:80,length:180,lower:50,upper:150,x:0,z:0,rotation:0};
export function parts(b:Bed):Part[]{const out:Part[]=[],heights=b.levels===2?[b.lower,b.upper]:[b.lower];const add=(a:Part['a'],c:Part['b'],radius=4)=>out.push({a,b:c,radius});for(const x of [-b.width/2+4,b.width/2-4])for(const z of [-b.length/2+4,b.length/2-4]){let y=0;for(const h of heights){add([x,y,z],[x,h-8,z]);add([x,h-8,z],[x,h,z],3);y=h;}add([x,y,z],[x,heights.at(-1)!+12,z]);}for(const h of heights){for(const x of [-b.width/2+4,b.width/2-4])add([x,h-4,-b.length/2+4],[x,h-4,b.length/2-4]);for(const z of [-b.length/2+4,b.length/2-4])add([-b.width/2+4,h-4,z],[b.width/2-4,h-4,z]);}return out;}
export function validate(b:Bed){if(b.levels!==1&&b.levels!==2)throw Error('Wybierz 1 lub 2 poziomy.');for(const k of ['width','length','lower','upper','x','z','rotation'] as const)if(typeof b[k]!=='number'||!Number.isFinite(b[k]))throw Error('Wpisz poprawną liczbę.');if(b.width<40||b.width>250||b.length<60||b.length>400)throw Error('Szerokość: 40–250 cm. Długość: 60–400 cm.');if(b.lower<12||b.lower>280||b.upper<12||b.upper>280)throw Error('Wysokość posłania: 12–280 cm.');if(b.levels===2&&b.upper<b.lower+10)throw Error('Górne posłanie musi być co najmniej 10 cm nad dolnym.');if(Math.abs(b.x)>1000||Math.abs(b.z)>1000)throw Error('Pozycja musi mieścić się w zakresie −1000–1000 cm.');if(![0,90,180,270].includes(b.rotation))throw Error('Obrót musi wynosić 0°, 90°, 180° lub 270°.');return b;}
export function bounds(b:Bed){const turned=b.rotation%180!==0;return {minX:b.x-(turned?b.length:b.width)/2,maxX:b.x+(turned?b.length:b.width)/2,minZ:b.z-(turned?b.width:b.length)/2,maxZ:b.z+(turned?b.width:b.length)/2};}
function world(p:number[],b:Bed){const t=b.rotation*Math.PI/180;return [b.x+p[0]*Math.cos(t)+p[2]*Math.sin(t),p[1],b.z-p[0]*Math.sin(t)+p[2]*Math.cos(t)];}
export function roofCollision(b:Bed){return parts(b).some(p=>{const a=world(p.a,b),c=world(p.b,b),d=c.map((v,i)=>v-a[i]),len=Math.hypot(...d),u=d.map(v=>v/len);return [-1,1].some(sign=>{const n=[sign*.45,1,0],dot=(v:number[])=>v.reduce((s,x,i)=>s+x*n[i],0),radial=p.radius*Math.sqrt(Math.max(0,1.2025-dot(u)**2));return Math.max(dot(a),dot(c))+radial>250+1e-7;});});}
export function collisions(beds:Bed[]){const result:Record<string,string[]>={};for(const b of beds){const box=bounds(b),errors:string[]=[];if(box.minX< -200-1e-7||box.maxX>200+1e-7||box.minZ< -250-1e-7||box.maxZ>250+1e-7)errors.push('Prycza wychodzi poza obrys namiotu.');if(roofCollision(b))errors.push('Żerdzie przecinają skos dachu.');for(const other of beds){if(other.id===b.id)continue;const o=bounds(other);if(box.minX<o.maxX-1e-7&&box.maxX>o.minX+1e-7&&box.minZ<o.maxZ-1e-7&&box.maxZ>o.minZ+1e-7){errors.push('Prycza nakłada się na inną pryczę.');break;}}result[b.id]=errors;}return result;}
export type Layout={beds:Bed[];selected:string|null};
export function nextLayout(state:Layout,action:{type:'add';levels:1|2}|{type:'update';id:string;patch:Partial<Bed>}|{type:'remove';id:string}|{type:'select';id:string|null}):Layout{
if(action.type==='select'){if(action.id&&!state.beds.some(b=>b.id===action.id))throw Error('Nie znaleziono pryczy.');return {...state,selected:action.id};}
if(action.type==='add'){let b:Bed=validate({id:crypto.randomUUID(),levels:action.levels,...defaults});let found=false;for(let z=-150;z<=150&&!found;z+=10)for(let x=-150;x<=150&&!found;x+=10){const candidate={...b,x,z};if(collisions([...state.beds,candidate])[b.id].length===0){b=candidate;found=true;}}return {beds:[...state.beds,b],selected:b.id};}
if(!state.beds.some(b=>b.id===action.id))throw Error('Nie znaleziono pryczy.');
if(action.type==='remove')return {beds:state.beds.filter(b=>b.id!==action.id),selected:state.selected===action.id?null:state.selected};
const allowed=['width','length','lower','upper','x','z','rotation'];if(Object.keys(action.patch).some(k=>!allowed.includes(k)))throw Error('Nieznany parametr pryczy.');return {...state,beds:state.beds.map(b=>b.id===action.id?validate({...b,...action.patch}):b)};
}
