'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {dispatch,getLayout,undo,redo,useHistory,useLayout} from './store';
import type {Layout} from './model';
type Saved={id:string;name:string;date:string;layout:Layout};
const KEY='pionierka-projects-v1';
export default function ProjectActions(){const layout=useLayout();const history=useHistory(),[open,setOpen]=useState(false),[name,setName]=useState('Mój namiot'),[saved,setSaved]=useState<Saved[]>([]),[message,setMessage]=useState('');const openProjects=()=>{setMessage('');try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');setSaved(Array.isArray(data)?data:[]);setOpen(true);}catch{setOpen(true);setMessage('Nie można odczytać zapisów w tej przeglądarce.')}};const save=()=>{if(!name.trim()){setMessage('Podaj nazwę projektu.');return;}try{const entry={id:crypto.randomUUID(),name:name.trim(),date:new Date().toISOString(),layout:getLayout()};const next=[entry,...saved];localStorage.setItem(KEY,JSON.stringify(next));setSaved(next);setMessage('Zapisano projekt: '+entry.name);}catch{setMessage('Nie udało się zapisać. Pamięć przeglądarki może być pełna lub zablokowana.')}};return <><div className="project-actions"><Button variant="outline" disabled={!history.canUndo} onClick={undo}>↶ Cofnij</Button><Button variant="outline" disabled={!history.canRedo} onClick={redo}>↷ Ponów</Button><Button variant="outline" onClick={openProjects}>Zapisz / otwórz</Button><Button variant="outline" onClick={()=>{dispatch({type:'reset'});setName('Nowy projekt')}}>Nowy projekt</Button><Button variant="outline" onClick={()=>window.print()}>Drukuj projekt</Button><Button variant="outline" disabled={!layout.beds.length} onClick={()=>dispatch({type:'clear'})}>Usuń wszystkie modele</Button></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>Zapisane projekty</DialogTitle><DialogDescription>Zapisy zostają w tej przeglądarce na tym urządzeniu. Każdy zapis tworzy osobną kopię. Usunięcie danych przeglądarki usuwa także projekty.</DialogDescription><label htmlFor="project-name">Nazwa projektu</label><Input id="project-name" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/><Button onClick={save}>Zapisz bieżący projekt</Button><p role="status">{message}</p><div className="saved-projects">{!saved.length?<p>Brak zapisanych projektów.</p>:saved.map(p=><div key={p.id}><div><b>{p.name}</b><small>{new Date(p.date).toLocaleString('pl-PL')} · {p.layout.beds.length} modeli</small></div><Button variant="outline" onClick={()=>{try{dispatch({type:'load',layout:p.layout});setName(p.name);setOpen(false)}catch{setMessage('Ten zapis jest niepoprawny i nie został otwarty.')}}}>Otwórz</Button></div>)}</div></DialogContent></Dialog></>}
