'use client';
import {useEffect} from 'react';
import {flushSync} from 'react-dom';
import {dispatch,getLayout} from './store';
import {collisions,materialList,connectionPairs,type Bed} from './model';
type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export function useWebMCP(){useEffect(()=>{const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const snapshot=()=>({...getLayout(),collisions:collisions(getLayout().beds),connections:connectionPairs(getLayout().beds),materials:materialList(getLayout().beds)});const obj=(raw:unknown)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Oczekiwano obiektu.');return raw as Record<string,unknown>};const mutate=(action:Parameters<typeof dispatch>[0])=>{flushSync(()=>dispatch(action));return snapshot();};const register=(name:string,description:string,inputSchema:object,execute:(input:unknown)=>unknown,readOnlyHint=false)=>{try{Promise.resolve(context.registerTool({name,description,inputSchema,annotations:{readOnlyHint,untrustedContentHint:false},execute},{signal:life.signal})).catch(console.warn);}catch(e){console.warn(e)}};
register('read_layout','Odczytaj prycze, zaznaczenie i kolizje w aktualnym projekcie.',{type:'object',properties:{},additionalProperties:false},snapshot,true);
register('add_bed','Dodaj i zaznacz pryczę w bieżącym projekcie.',{type:'object',properties:{levels:{type:'integer',enum:[1,2]}},required:['levels'],additionalProperties:false},raw=>{const v=obj(raw);if(Object.keys(v).some(k=>k!=='levels')||(v.levels!==1&&v.levels!==2))throw Error('Wymagany levels: 1 lub 2.');return mutate({type:'add',levels:v.levels})});
register('update_bed','Zmień wymiary, pozycję lub obrót istniejącej pryczy. Jednostka: cm; obrót: stopnie.',{type:'object',properties:{id:{type:'string'},patch:{type:'object',properties:Object.fromEntries(['width','length','lower','upper','x','z','rotation'].map(k=>[k,{type:'number'}])),additionalProperties:false}},required:['id','patch'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||Object.keys(v).some(k=>!['id','patch'].includes(k)))throw Error('Wymagane id i patch.');return mutate({type:'update',id:v.id,patch:obj(v.patch) as Partial<Bed>})});
register('remove_bed','Usuń wskazaną pryczę z projektu.',{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||Object.keys(v).some(k=>k!=='id'))throw Error('Wymagane id.');return mutate({type:'remove',id:v.id})});register('join_beds','Dosuń wskazaną pryczę do długiego boku drugiej, łącząc wspólne słupki i belki. Wymagana ta sama długość i równoległe ustawienie.',{type:'object',properties:{id:{type:'string'},targetId:{type:'string'}},required:['id','targetId'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||typeof v.targetId!=='string'||Object.keys(v).some(k=>!['id','targetId'].includes(k)))throw Error('Wymagane id i targetId.');return mutate({type:'join',id:v.id,targetId:v.targetId})});return()=>life.abort();},[])}

