'use client';
import {useEffect} from 'react';
import {flushSync} from 'react-dom';
import {dispatch,getLayout,undo,redo} from './store';
import {collisions,materialList,connectionPairs,type JoinSide,type Bed} from './model';
type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export function useWebMCP(){useEffect(()=>{const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const snapshot=()=>({...getLayout(),collisions:collisions(getLayout().beds),connections:connectionPairs(getLayout().beds),materials:materialList(getLayout().beds)});const obj=(raw:unknown)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Oczekiwano obiektu.');return raw as Record<string,unknown>};const mutate=(action:Parameters<typeof dispatch>[0])=>{flushSync(()=>dispatch(action));return snapshot();};const register=(name:string,description:string,inputSchema:object,execute:(input:unknown)=>unknown,readOnlyHint=false)=>{try{Promise.resolve(context.registerTool({name,description,inputSchema,annotations:{readOnlyHint,untrustedContentHint:false},execute},{signal:life.signal})).catch(console.warn);}catch(e){console.warn(e)}};
register('read_layout','Odczytaj prycze, zaznaczenie i kolizje w aktualnym projekcie.',{type:'object',properties:{},additionalProperties:false},snapshot,true);
register('undo_layout','Cofnij ostatnią zmianę.',{type:'object',properties:{},additionalProperties:false},()=>{flushSync(undo);return snapshot()});
register('redo_layout','Ponów cofniętą zmianę.',{type:'object',properties:{},additionalProperties:false},()=>{flushSync(redo);return snapshot()});
register('change_bed_levels','Dodaj lub usuń najwyższy poziom pryczy. Zachowuje wysokości istniejących posłań.',{type:'object',properties:{id:{type:'string'},delta:{type:'integer',enum:[-1,1]}},required:['id','delta'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||(v.delta!==1&&v.delta!==-1))throw Error('Podaj id i delta.');return mutate({type:'bed-level',id:v.id,delta:v.delta})});
register('clear_layout','Usuń wszystkie modele z bieżącego projektu.',{type:'object',properties:{},additionalProperties:false},()=>mutate({type:'clear'}));
register('change_shelf_levels','Dodaj lub usuń poziom regału, zachowując wysokość i równe odstępy.',{type:'object',properties:{id:{type:'string'},delta:{type:'integer',enum:[-1,1]}},required:['id','delta'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||(v.delta!==1&&v.delta!==-1))throw Error('Podaj id i delta: 1 lub -1.');return mutate({type:'shelf-level',id:v.id,delta:v.delta})});
register('add_shelf','Dodaj regał o trzech edytowalnych poziomach.',{type:'object',properties:{},additionalProperties:false},()=>mutate({type:'add',kind:'shelf',levels:3}));
register('add_bed','Dodaj i zaznacz pryczę w bieżącym projekcie.',{type:'object',properties:{levels:{type:'integer',enum:[1,2]}},required:['levels'],additionalProperties:false},raw=>{const v=obj(raw);if(Object.keys(v).some(k=>k!=='levels')||(v.levels!==1&&v.levels!==2))throw Error('Wymagany levels: 1 lub 2.');return mutate({type:'add',levels:v.levels})});
register('update_bed','Zmień wymiary, pozycję lub obrót istniejącej pryczy. Jednostka: cm; obrót: stopnie.',{type:'object',properties:{id:{type:'string'},patch:{type:'object',properties:Object.fromEntries(['middle','width','length','lower','upper','x','z','rotation'].map(k=>[k,{type:'number'}])),additionalProperties:false}},required:['id','patch'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||Object.keys(v).some(k=>!['id','patch'].includes(k)))throw Error('Wymagane id i patch.');return mutate({type:'update',id:v.id,patch:obj(v.patch) as Partial<Bed>})});
register('remove_bed','Usuń wskazaną pryczę z projektu.',{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||Object.keys(v).some(k=>k!=='id'))throw Error('Wymagane id.');return mutate({type:'remove',id:v.id})});register('join_beds','Dosuń konstrukcję do dowolnego boku innej pryczy lub regału, łącząc wspólne żerdzie.',{type:'object',properties:{id:{type:'string'},targetId:{type:'string'},side:{type:'string',enum:['left','right','back','front']}},required:['id','targetId'],additionalProperties:false},raw=>{const v=obj(raw);if(typeof v.id!=='string'||typeof v.targetId!=='string'||Object.keys(v).some(k=>!['id','targetId','side'].includes(k)))throw Error('Wymagane id i targetId.');if(v.side!==undefined&&!['left','right','back','front'].includes(String(v.side)))throw Error('Niepoprawna strona.');return mutate({type:'join',id:v.id,targetId:v.targetId,side:v.side as JoinSide|undefined})});return()=>life.abort();},[])}

